controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute






# FROM THE DOCUMENTATION ***********************************************************************************
# Matching HTTP Methods ---------------------------------------
#api_post_show:
#    path:       /api/posts/{id}
#    controller: App\Controller\BlogApiController::show
#    methods:    GET|HEAD

#api_post_edit:
#    path:       /api/posts/{id}
#    controller: App\Controller\BlogApiController::edit
#    methods:    PUT
# -------------------------------------------------------------

# Matching Expressions ----------------------------------------
###
# -------------------------------------------------------------

# Parameters Validation ---------------------------------------
###
# -------------------------------------------------------------

# Optional Parameters -----------------------------------------
### defaults values for the routes 
# -------------------------------------------------------------

